site_name: pat_data_processing
theme: readthedocs

nav:
  - Home: index.md
  - PAT Data Structure: pat_data_structure.md
  - CLI Usage: cli.md
  - Compute Score: compute_score.md
  - Compile Answers: compile_answers.md
  - Compile Questionnaires: compile_questionnaires.md
  - Wrangle Data: wrangle_data.md
  - Utils: utils.md
  - Rand YAML: rand_yaml.md
  - Structure JSON: structure_json.md
